### ISSUE TITLE
Add assets

### ISSUE THREAD

**Issue by jtucker2** [Spyderisk/domain-csv2doc#14]
There should be a page for each asset in ```DomainAsset.csv``` which includes:
- The display name (label)
- The URI
- The description

**Comment by scp93ch** [comment]
The icon would be great as well.

The icons are in a different folder to the CSVs, so as csv2doc is currently using an argument pointing at the CSV files, it would need changing to be an argument pointing at the domain model folder that contains the `csv` and `icons` folders.
